const global = require('@/assets/ranks/global.png')
const supreme = require('@/assets/ranks/supreme.png')
const lem = require('@/assets/ranks/lem.png')
const eagle = require('@/assets/ranks/eagle.png')
const sherif = require('@/assets/ranks/sherif.png')
const doubleAk = require('@/assets/ranks/double-ak.png')
const ak1 = require('@/assets/ranks/ak-1.png')
const ak = require('@/assets/ranks/ak.png')
const gold4 = require('@/assets/ranks/gold-4.png')
const gold3 = require('@/assets/ranks/gold-3.png')
const gold2 = require('@/assets/ranks/gold-2.png')
const gold1 = require('@/assets/ranks/gold-1.png')
const silverEliteMaster = require('@/assets/ranks/silver-elite-master.png')
const silverElite = require('@/assets/ranks/silver-elite.png')
const silver4 = require('@/assets/ranks/silver-4.png')
const silver3 = require('@/assets/ranks/silver-3.png')
const silver2 = require('@/assets/ranks/silver-2.png')
const silver1 = require('@/assets/ranks/silver-1.png')
const unranked = require('@/assets/ranks/unranked.png')
const expired = require('@/assets/ranks/expired.png')

export enum Rank{
  GLOBAL = global,
  SUPREME = supreme,
  LEM = lem,
  EAGLE = eagle,
  SHERIF = sherif,
  DOUBLE_AK = doubleAk,
  AK1 = ak1,
  AK = ak,
  GOLD4 = gold4,
  GOLD3 = gold3,
  GOLD2 = gold2,
  GOLD1 = gold1,
  SILVER_ELITE_MASTER = silverEliteMaster,
  SILVER_ELITE = silverElite,
  SILVER4 = silver4,
  SILVER3 = silver3,
  SILVER2 = silver2,
  SILVER1 = silver1,
  UNRANKED = unranked,
  EXPIRED = expired
}
